<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: greeting.proto

namespace Greeting;

use Spiral\GRPC;

interface GreeterInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "greeting.Greeter";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HelloRequest $in
    * @return HelloReply
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SayHello(GRPC\ContextInterface $ctx, HelloRequest $in): HelloReply;
}
